-- dap.adapters.java = function(callback)
--   -- FIXME:
--   -- Here a function needs to trigger the `vscode.java.startDebugSession` LSP command
--   -- The response to the command must be the `port` used below
--   callback({
--     type = 'server';
--     host = '127.0.0.1';
--     port = port;
--   })
-- end
--
--dap.adapters.java = function(callback, config)
--  M.execute_command({ command = 'vscode.java.startDebugSession' }, function(err0, port)
--    assert(not err0, vim.inspect(err0))
--    callback({ type = 'server', host = '127.0.0.1', port = port, })
--  end)
--end
